### ISSUE TITLE
#3: Consult drone documentation ( 3-6-9) 

### ISSUE THREAD

**Issue by ciungucristian** [ciungucristian/drone#3]

**Comment by Oussama99-OM** [comment]
The useful sources that can be used are:

- https://github.com/liourej/CodeDroneDIY#softwareSetup
Best source I was able to find so far with very detailed steps to building our own DIY Arduino Drone.


- https://github.com/ArduProject/DroneArduino_v1
Comes with a website (https://arduproject.es) that has qualitative description of the protocol used.
I picked this source since it seemed to have way less code than all the other sources. The only issue with this source is that the blog is written in Spanish.

Most other sources I found online lacked documentation and were harder to understand.

**Comment by ciungucristian** [comment]
Great stuff Oussama! We'll close this issue after going over the documents next Sunday!

**Comment by ciungucristian** [comment]
After going over the documentation that Oussama found, we decided to go with the source that is not in Spanish.
